version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
    - "5001:5000"
    volumes:
    - .:/app
    links:
    - mongo
    depends_on: 
      - mongo
    networks: 
      - flask_network
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   volumes:
  #     - mongo-data:/data/db
  #     - mongo-configdb:/data/configdb
  #   ports: 
  #     - 27017:27017
  #   command: mongod
  mongo:
    restart: always
    image: mongo:4.2
    ports:
      - 27017:27017
    command: mongod
    networks: 
      - flask_network

networks: 
  flask_network:
    name: flask_network