version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
    - "5001:5000"
    volumes:
    - .:/app
    links:
    - mongo
    networks: 
      - flask_network
  mongo:
    restart: always
    image: mongo:4.2
    ports:
      - 27017:27017
    command: mongod
    networks: 
      - flask_network

networks: 
  flask_network:
    name: flask_network